using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using CleanCode.Code;
using CleanCode.Gui.Forms;
using CleanCode.DataBase.SqlServer.EFModel;

namespace CleanCode.Gui.UsersControl
{
    public partial class UsersPageUserControl : DevExpress.XtraEditors.XtraUserControl
    {

        private IdataHelper<UserTable> usertableControlor;
        public UsersPageUserControl()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            usertableControlor = new UsersControler();
            UpdateGridView();
        }
        #region Events
       
        #endregion
        private void gridView1_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            MessageBox.Show(gridView1.GetRowCellValue(e.RowHandle, "Id").ToString());
        }

        public void UpdateGridView()
        {
            gridControl1.DataSource = usertableControlor.GetAllData();
        }

        private void ID_BtnAdd_Click(object sender, EventArgs e)
        {
            FormUsers formUsers = new FormUsers(0,this);
            formUsers.ID_BtnSave.Text = "ADD User";
            formUsers.Show();
        }
    }
}
